### ISSUE TITLE
Proxy does not work

### ISSUE THREAD

**Issue by 0-BuTaJIuK-0** [LUXTACO/SteamGen#3]
███████╗████████╗███████╗ █████╗ ███╗   ███╗ ██████╗ ███████╗███╗   ██╗
                        ██╔════╝╚══██╔══╝██╔════╝██╔══██╗████╗ ████║██╔════╝ ██╔════╝████╗  ██║
                        ███████╗   ██║   █████╗  ███████║██╔████╔██║██║  ███╗█████╗  ██╔██╗ ██║
                        ╚════██║   ██║   ██╔══╝  ██╔══██║██║╚██╔╝██║██║   ██║██╔══╝  ██║╚██╗██║
                        ███████║   ██║   ███████╗██║  ██║██║ ╚═╝ ██║╚██████╔╝███████╗██║ ╚████║
                        ╚══════╝   ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═══╝

========================================================================================================================

                                                >> Made By Taquito
                                                >> Version 1.0

                                          >> Accounts to generate: 2
                                           >> Use proxies? (Y/N): y

1.162.28.93:80
Proxy is working...

DevTools listening on ws://127.0.0.1:53404/devtools/browser/01f43795-915d-4a09-b2ab-3d571d0c8457
Traceback (most recent call last):
  File "C:\Users\Test\Desktop\SteamGen-main\main.py", line 139, in <module>
    driver.find_element(By.ID, "email").send_keys(email)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Test\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Test\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Test\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="email"]"}
  (Session info: chrome=110.0.5481.178)
Stacktrace:
Backtrace:
        (No symbol) [0x009837D3]
        (No symbol) [0x00918B81]
        (No symbol) [0x0081B36D]
        (No symbol) [0x0084D382]
        (No symbol) [0x0084D4BB]
        (No symbol) [0x00883302]
        (No symbol) [0x0086B464]
        (No symbol) [0x00881215]
        (No symbol) [0x0086B216]
        (No symbol) [0x00840D97]
        (No symbol) [0x0084253D]
        GetHandleVerifier [0x00BFABF2+2510930]
        GetHandleVerifier [0x00C28EC1+2700065]
        GetHandleVerifier [0x00C2C86C+2714828]
        GetHandleVerifier [0x00A33480+645344]
        (No symbol) [0x00920FD2]
        (No symbol) [0x00926C68]
        (No symbol) [0x00926D4B]
        (No symbol) [0x00930D6B]
        BaseThreadInitThunk [0x765EFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77717A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77717A6E+238]

**Comment by LUXTACO** [comment]
Im aware of this issues an they are mostly caused because I didnt use the try: and except:, I know rookie mistake im working on a fix tho
